language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23 #failed to find build-tools-23.0.3
    - extra-android-m2repository
    - extra-google-m2repository

# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
before_install:
    - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
