language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository

# http://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
before_install:
    - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
